# Generated by Django 5.1.6 on 2025-05-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('dependents', models.CharField(max_length=10)),
                ('married', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=20)),
                ('applicant_income', models.FloatField()),
                ('coapplicant_income', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('loan_amount_term', models.FloatField()),
                ('credit_history', models.FloatField()),
                ('self_employed', models.CharField(max_length=10)),
                ('property_area', models.CharField(max_length=20)),
                ('prediction_result', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
