# Generated by Django 5.1.6 on 2025-05-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanprediction',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='loanprediction',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanprediction',
            name='prediction_result',
            field=models.CharField(max_length=20),
        ),
    ]
