# Generated by Django 5.1.6 on 2025-06-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_alter_loanprediction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanprediction',
            name='user',
        ),
        migrations.AlterField(
            model_name='loanprediction',
            name='prediction_result',
            field=models.CharField(max_length=20),
        ),
    ]
