# Generated by Django 5.0.13 on 2025-06-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_remove_loanprediction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprediction',
            name='loan_type',
            field=models.CharField(default='Personal', max_length=20),
        ),
    ]
