# Generated by Django 5.0.13 on 2025-06-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_loanprediction_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprediction',
            name='loan_type',
            field=models.CharField(max_length=20),
        ),
    ]
