# Generated by Django 5.0.13 on 2025-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_alter_loanprediction_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprediction',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
