# Generated by Django 5.0.13 on 2025-06-17 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_loanprediction_is_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprediction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
